### ISSUE TITLE
"Залипание" отрисовки на doTimeStep

### ISSUE THREAD

**Issue by avasyukov** [KonstantinKurochka/2zadanie#1]
К концу семинара у меня был уже сильно замылен глаз. Сейчас я выдохнул и нашёл проблему, почему отрисовка "залипала" на первом кадре. Проблема вот здесь:
https://github.com/KonstantinKurochka/2zadanie/blob/6be33d762df7e560ed17ceb9b15469b26abcd8e2/graphic_for_N_bodies.cpp#L256-L269

Здесь де-факто написано "и считать до конца процесса" (до времени 1.5 с малым шагом dt). Это куча "кадров". Но отрисовщик предполагает, что он рисует новый "кадр" после возврата из doTimeStep. Вот он и ждёт.

Итого: doTimeStep нужно поправить.

**Comment by KonstantinKurochka** [comment]
Убран цикл for.

**Comment by avasyukov** [comment]
Ок. Выполнено, этот тикет закрываю.

Насчёт результатов расчётов и подробностей реализации ещё накидаю новых тикетов чуть позже.
