### ISSUE TITLE
Расчёт силы взаимодействия

### ISSUE THREAD

**Issue by avasyukov** [KonstantinKurochka/2zadanie#2]
Вот такой расчёт силы:
https://github.com/KonstantinKurochka/2zadanie/blob/4dee666390a05a4836d1bede37a21270a835e4a6/graphic_for_N_bodies.cpp#L185-L189
некорректен.

Например, можно наблюдать вот такое:
```
Body #1: -4.95346 0.0159523 (m = 100)
Body #2: 0.346251 8.40466 (m = 1)
Force: 5.38275 8.52014
```
Массы 1 и 100, расстояние около 10. Сила явно не около 1.

**Comment by KonstantinKurochka** [comment]
Расчёт численного значения силы проводился по закону всемирного тяготения без константы: F = m1 * m2 / r^2.

Для этих данных:
F = (1 * 100)/ 98.48 = 1.015.

Далее это число умножается на вектор, соединяющий два тела. В расчётах используется именно вектор силы, т.к. из него получается вектор ускорения, а затем вектор скорости. То есть вектор силы считается верно с точностью до константы умножения.

**Comment by avasyukov** [comment]
Всё хорошо, тикет закрываю
